### ISSUE TITLE
timelock-worker: use a Clock interface for worker timing

### ISSUE THREAD

**Issue by MStreet3** [smartcontractkit/timelock-worker#34]
The `dumpOperationStore` method of the `Worker` accepts a `func() time.Time` for getting the current time of the log dump.  This could instead be replaced by adding a `Clock` interface to the `Worker` as a dependency:

```go
type Clock interface {
    Now() time.Time
}

type Worker struct {
    // other members
    clock Clock
}
```

introduced by #33 

Could alternatively be resolved by separating the store from the worker completely and leaving this as an implementation detail of the store.

**Comment by gustavogama-cll** [comment]
Converted to Jira ticket: https://smartcontract-it.atlassian.net/browse/DPA-1286
