### ISSUE TITLE
timelock-worker should be ABI agnostic

### ISSUE THREAD

**Issue by fbac** [smartcontractkit/timelock-worker#39]
`operations.go` define a set of methods to interact which interact closely with the RBACTimelock.sol ABI operations. Instead of this, timelock-worker should be agnostic to the contract ABI.

Implement an interface which abstract contract ABI methods, so timelock-worker core can inject an interface agnostic to the contract on the backend.

**Comment by gustavogama-cll** [comment]
Converted to Jira ticket: https://smartcontract-it.atlassian.net/browse/DPA-1285
